### ISSUE TITLE
Some crashes/issues on GUI

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#31]
From: @niuus

These issues on the GUI can break the WiiSXRX_2022 emulator:
- If you load a game, then return to emulator menu. Enter Settings, change "Boot Trough Bios" to "No", and press down, it causes an instant DSI code dump error. Same issue happens if you don't load a game.
- If you load the emulator, then press "Quit" and then "OK" without loading a game, it causes an instant DSI code dump error.
- If you load the emulator, then press "Settings", and then "Execute Bios", it causes an instant ISI code dump error.

Using a build i've compiled with latest commits on main branch until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/fd473d5e2a978169f6dab0c47f291b071c899b58

**Comment by saulfabregwiivc** [comment]
More issues on GUI of WiiSXRX_2022 reported by @niuus:

- Have a folder called "Lost World, The - Jurassic Park - Special Edition (USA)" inside the isos folder. If the game file inside exceeds 52 characters, it will say "Failed to load ISO". Under the same circumstances, open the folder, but don't load the game. Press ".." once, and enter the folder again. Instant DSI crash.
- Have a folder called "2022" inside the isos folder. Inside the "2022" folder, create another folder called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)". Have the bin+cue inside, called the same as the folder. Whichever you load, it will say "Failed to load ISO".
Under the same circumstances, open the folder, but don't load the game. Press ".." once, and enter the folder again. Instant DSI crash.
- Have a folder called "2022" inside the isos folder. Inside the "2022" folder, create another folder called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)". Have the bin called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (" and the cue called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)" inside. Press ".." once, and enter the folder again. The filename will display 3 characters only. If you press "..." again, filenames will disappear. Press B to go back to normal. In this example, you can load the bin but only if it doesn't exceed 47 characters.

**Comment by carnage702** [comment]
> More issues on GUI of WiiSXRX_2022 reported by @niuus:
> 
>     * Have a folder called "Lost World, The - Jurassic Park - Special Edition (USA)" inside the isos folder. If the game file inside exceeds 52 characters, it will say "Failed to load ISO". Under the same circumstances, open the folder, but don't load the game. Press ".." once, and enter the folder again. Instant DSI crash.
> 
>     * Have a folder called "2022" inside the isos folder. Inside the "2022" folder, create another folder called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)". Have the bin+cue inside, called the same as the folder. Whichever you load, it will say "Failed to load ISO".
>       Under the same circumstances, open the folder, but don't load the game. Press ".." once, and enter the folder again. Instant DSI crash.
> 
>     * Have a folder called "2022" inside the isos folder. Inside the "2022" folder, create another folder called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)". Have the bin called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (" and the cue called "Dragon Ball Z - Idainaru Dragon Ball Densetsu (Japan)" inside. Press ".." once, and enter the folder again. The filename will display 3 characters only. If you press "..." again, filenames will disappear. Press B to go back to normal. In this example, you can load the bin but only if it doesn't exceed 47 characters.

same happens if the isos have special characters in them it will fail to load iso if the games have characters like  "," or "&" or any special character in general.

**Comment by xjsxjs197** [comment]
Increase the length of the path buffer, This problem should be solved. Please help test

**Comment by saulfabregwiivc** [comment]
> From: @niuus
> 
> These issues on the GUI can break the WiiSXRX_2022 emulator:
> 
> * If you load a game, then return to emulator menu. Enter Settings, change "Boot Trough Bios" to "No", and press down, it causes an instant DSI code dump error. Same issue happens if you don't load a game.
> * If you load the emulator, then press "Quit" and then "OK" without loading a game, it causes an instant DSI code dump error.
> * If you load the emulator, then press "Settings", and then "Execute Bios", it causes an instant ISI code dump error.
> 
> Using a build i've compiled with latest commits on main branch until git [fd473d5](https://github.com/xjsxjs197/WiiSXRX_2022/commit/fd473d5e2a978169f6dab0c47f291b071c899b58)

@xjsxjs197 

These issues aren't still solved. I've compiled latest code and these problems are still here.
I don't know how the BIN+CUE files react to the new path buffer, maybe @carnage702 can help?

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 

I've compiled today main branch until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/a958d1724077853a7f6f0c1a1569d4ded153795c and i've tested it,
but sadly the only problem solved is:

- If you load a game, then return to emulator menu. Enter Settings, change "Boot Trough Bios" to "No", and press down, it causes an instant DSI code dump error. Same issue happens if you don't load a game.

These issues still occurs:

- If you load the emulator, then press "Quit" and then "OK" without loading a game, it causes an instant ISI (not DSI) error.
- If you load the emulator, then press "Settings", and then "Execute Bios", it causes an instant ISI error.

**Comment by xjsxjs197** [comment]
The remaining problems should be solved

**Comment by saulfabregwiivc** [comment]
OK, i've tested the new build and now the crashes mentioned aren't occurring anymore.
Thanks @xjsxjs197!

Can you tell me in what commit did you fix these?

**Comment by xjsxjs197** [comment]
> Can you tell me in what commit did you fix these?

https://github.com/xjsxjs197/WiiSXRX_2022/commit/7669390beef92c0396aff3c32f579512e8629ec4
Two correction points:
  When the ISO is not loaded, do not need to call SysClose. (MainFrame.cpp)
  When the ISO is not loaded, call ISOopen and return the normal value. (cdriso.c)
